HEADLESS_HELP_STRING = """This script can be in two modes.
Run the script without arguments: CLI mode with all supported features.
Run the script with arguments: headless single-prompt mode.
By default, internet and functions are disabled for headless-mode.
Reprompting is not supported in headless-mode.

========================
Headless-mode modes:
========================
- text-to-text (default)
- text-to-image
- image-to-text

========================
Headless-mode arguments:
========================
[Required]
--prompt="<prompt>"         : the prompt to process
--image="<imagepath>"       : image path (only required for image-to-x modes)

[Optional]
--mode="<mode>"             : set the operation mode (unset = text-to-text)
--model="<modelname>"       : set the model to use (unset = config)
--convo="<filename>"        : set the conversation file in output/conversations/ (unset = new file)
--functions                 : enable functions for this prompt
--internet                  : enable internet for this prompt
--system_prompt="<prompt>   : set the system prompt (unset = config)"
--debug_level=X             : set the debug level (unset = 0)
--line_break_threshold=X    : set the line-break threshold (unset = config)"""
COMMANDS_NOT_ALLOWED_STRING = "You cannot use commands in headless mode."
INPUT_PROMPT_STRING = "Enter a prompt (\"/help\" for list of commands)"
MUST_INPUT_IMAGE_STRING = "You must provide an image."
MUST_INPUT_PROMPT_STRING = "You must provide a prompt."
UNKNOWN_ARGUMENT_STRING = "Unknown argument: "
UNSUPPORTED_MODE_STRING = "Unsupported mode: "
ERROR_OCCURRED_STRING = "An error has occurred: "
RECORDING_ENDING_STRING = "Stopping recording"
RECORDING_FINISHED_STRING = "Recording finished."
INVALID_CHAT_HISTORY_FORMAT_STRING = "The following string is not in a valid 'role:content' form: "
MODEL_NOT_FOUND_STRING = "No model found with name: "
FILE_DELETE_DISABLED_CANNOT_UPDATE_MODELS_STRING = """
You have disabled 'disable_all_file_delete_functions'.
This configuration must be disabled in order to update your model configuration.
Not updating model list.
"""
MODELS_UPDATED_STRING = "Successfully updated your models.json."
MODELS_UPDATE_ERROR_STRING = "Could not update your models.json - check your connection."
NEW_MODELS_JSON_STRING = "New models.json: "
NEW_MODEL_FOUND_STRING = "Found new model: "
FUNCTIONS_DISABLED_STRING = "Functions are disabled - using chat completion only."
CALLING_TRIGGER_STRING = "Calling trigger: "
TRIGGER_NO_RESULT_STRING = "No result for this trigger - stopping trigger detection."
CALLING_BEST_TRIGGER_STRING = "Calling best-matched trigger: "
NO_MORE_TRIGGERS_STRING = "No more triggers detected."
NO_TRIGGERS_STRING = "No triggers detected."
NO_INTERNET_SKIP_EMBEDDED_STRING = "Internet is disabled - skipping embedded website check."
FOUND_EMBEDDED_STRING = "Found website in file: "
OPENING_FOLDER_STRING = "Opening folder: "
FILES_IN_FOLDER_STRING = "Files in folder: "
PARSING_FILE_STRING = "Parsing file: "
FILE_CONTENT_STRING = "File content: "
RETRIEVED_TEXT_STRING = "Retrieved text from: "
WEBSITE_TEXT_STRING = "Website text: "
CANNOT_GET_FILE_CONTENTS_STRING = "Cannot get file contents."
FOUND_PROMPT_FILE_STRING = "Found a prompt file."
PROMPT_FILE_STRING = "Prompt in file: "
FILE_SKIPPED_NO_SLASH_STRING = "File skipped it is missing a slash: "
TARGET_LINKS_STRING = "Target links: "
FETCH_SOURCE_FAILED_STRING = "Failed to fetch a source."
NO_SOURCES_COMPILED_STRING = "No sources were compiled."
SEARCH_TERMS_STRING = "Search term(s): "
DDG_RETRY_LIMIT_REACHED_EXIT_STRING = "Couldn't load DuckDuckGo after 3 tries - aborting search."
DDG_EXCEPTION_RETRY_STRING = "Exception thrown searching DuckDuckGo, trying again in 5 seconds..."
DDG_RATE_LIMITED_STRING = "(Rate limited - try opening DDG in a browser to reset the limit)"
RETRIEVING_TEXT_STRING = "Getting text from: "
WEBSITE_TEXT_FAIL_STRING = "Could not fetch resource from website: "
WEBSITE_JS_FAIL_STRING = "Website failed JS test: "
WEBSITE_ERROR_FAIL_STRING = "Website failed error test: "
RETRIEVED_TEXT_TRIMMED_STRING = "Fetched trimmed text from: "
AUTOGENERATED_CAPTIONS_STRING = "This transcript is auto-generated - it may not be correct."
VIDEO_CAPTIONS_STRING = "Video captions: "
NO_VIDEO_CAPTIONS_STRING = "Subtitles are disabled for this video"
VIDEO_CAPTIONS_ERROR_STRING = "An error occured obtaining the captions for this video."
VIDEO_ID_STRING = "Video ID: "


def getKeyInterferenceString(key):
    return f"""Note: This script can interfere with the use of the [{key}] key.
Remap this in code if needed."""


def getKeyStopRecordingString(key):
    return f"\nUse [{key}] to exit and save recording.\n"


def getConfigModelNotFoundString(modelType, availModel):
    return f"Configuration-specified {modelType} model not found - using {availModel}."


def getConfigModelNotDefinedString(modelType):
    return f"Cannot find a(n) {modelType} model - configure a model in order to use this functionality."
